# Generated by Django 4.2.6 on 2023-10-21 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=100)),
                ('frequency_occurrence', models.IntegerField()),
                ('severity_occurrence', models.IntegerField()),
                ('chance_detection', models.IntegerField()),
                ('active', models.BooleanField(default=1)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('action_plan', models.JSONField(null=True)),
                ('contingency_measures', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_applied', models.CharField(max_length=100)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('observations', models.CharField(blank=True, max_length=250)),
                ('risks_observed', models.ManyToManyField(related_name='risks_observed', to='ep.risk')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
