# Generated by Django 4.2.6 on 2023-10-12 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=datetime.datetime(2023, 10, 12, 14, 12, 6, 312995))),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=100)),
                ('frequency_occurrence', models.IntegerField()),
                ('severity_occurrence', models.IntegerField()),
                ('chance_detection', models.IntegerField()),
                ('active', models.BooleanField(default=1)),
                ('date_creation', models.DateField(default=datetime.datetime(2023, 10, 12, 14, 12, 6, 312995))),
            ],
        ),
    ]
