# Generated by Django 4.2.6 on 2023-10-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='observations',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='forms',
            name='risks_observed',
            field=models.ManyToManyField(to='checklist.risk'),
        ),
        migrations.AddField(
            model_name='forms',
            name='who_applied',
            field=models.CharField(default='Henrique Fernandes', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forms',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 17, 47, 29, 447091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 17, 47, 29, 446091, tzinfo=datetime.timezone.utc)),
        ),
    ]
