# Generated by Django 4.2.5 on 2023-10-16 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_form_date_creation_alter_form_risks_observed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='form',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 22, 19, 40, 519750, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 22, 19, 40, 519750, tzinfo=datetime.timezone.utc)),
        ),
    ]
