# Generated by Django 4.2.5 on 2023-10-16 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_form_options_alter_form_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 22, 29, 10, 583034, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 22, 29, 10, 583034, tzinfo=datetime.timezone.utc)),
        ),
    ]
