# Generated by Django 4.2.5 on 2023-10-17 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_form_date_creation_alter_risk_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
